### ISSUE TITLE
Summary shows for wrong feed

### ISSUE THREAD

**Issue by ehabebeid** [CUTR-at-USF/gtfs-realtime-validator#256]
**Summary:** 

When running the GTFS-RT Validator on both a service alerts feed and a vehicle positions one, the 
vehicle positions summary/error section is is displayed for both. When I click on an iteration, the feed messages are displayed properly but the error messages are still there.

**Platform:** 
Windows 7. Chrome/Firefox

**Error Summary**
![errorsummary](https://user-images.githubusercontent.com/16144005/28289034-3a490654-6b0f-11e7-882f-3476f508fad0.PNG)

**Iteration Summary for an Empty Service Alerts .PB file**
![iteration](https://user-images.githubusercontent.com/16144005/28289033-3a477c08-6b0f-11e7-949c-aed9dec0a04d.PNG)

In both cases the compiled protobuf files are written as .txt because of server restrictions.

**Comment by barbeau** [comment]
Thanks @ehabebeid, we'll take a look.  I believe I saw this myself the other day for a TripUpdates + VehiclePositions feed.  Were you monitoring any other feeds simultaneously in another browser?  In other words, was there more than one web client communicating with your server?  Please note that currently if you start a session, close the browser, and then come back to the browser without killing the server in between, this counts as simultaneous feed monitoring (we're working on fixing this in https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/215).

@Suryakandukoori Could you please take a look at this?  It may be related to the multiple clients issue (https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/215).

**Comment by ehabebeid** [comment]
Thanks @barbeau for your prompt reply. This might have been the case actually, but I killed the server, made sure localhost:8080 doesn't return anything, and reran validator. The bug persists.

**Comment by Suryakandukoori** [comment]
@barbeau, fix for #215 would fix this issue.

**Comment by barbeau** [comment]
Fixed via https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/257.

**Comment by barbeau** [comment]
@ehabebeid Could you please try again with the master branch, or as soon as Travis finishes building with the changes from https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/257 the JAR linked in the README and let us know if you still see the issue?

**Comment by ehabebeid** [comment]
It seems like the issue is still there. I redownloaded the JAR and reran it. Since I only have errors/warnings in the Vehicle Positions feed, I am not sure if it's showing the vehicle positions errors or just _all_ errors for all feeds.
![image](https://user-images.githubusercontent.com/16144005/28480491-e77c519c-6e2e-11e7-988a-81fe58e1de30.png)

**Comment by barbeau** [comment]
Ok, thanks. Reopening. 

@Suryakandukoori could you please take a look? Easiest was to repro is probably a service alert feed and trip update feed together.

**Comment by barbeau** [comment]
@Suryakandukoori have you started implementing any code to fix this issue? If not, let me know - I have a hypothesis as to what's happening and if I'm correct I can fix quickly in code.

**Comment by barbeau** [comment]
Per our discussion offline I'll take this issue.

**Comment by barbeau** [comment]
Ok, so it seems here is what's happening - when this tool was originally built, some of the first rules written were for cross-referencing errors between two feeds (i.e., rules `W003` and `E047` in what is now `CrossFeedDescriptorValidator`).  So, for each iteration, `BackgroundTask` around line 167 grabs all the GTFS-rt messages for all GTFS-rt feeds that are being monitored simultaneously for the same GTFS data from the database and this `combinedFeed` is passed into the rules to be validated.

The problem with this is just that - other rules implemented in the other validator classes such as `VehicleValidator` are running on ALL messages from ALL GTFS-rt feeds associated with the same GTFS data.  As a result, everything works fine when only one GTFS-rt feed per GTFS is running, but errors mix across multiple feeds when multiple GTFS-rt feeds are being monitored for the same GTFS data.

The simplest way to fix this is to add another method parameter to our `FeedEntityValidator` interface that all rules implement specifically for the `combinedFeedMessage`, and pass in only the `currentFeedMessage` for the `feedMessage` parameter.  `CrossFeedDescriptorValidator` will only validate the `combinedFeedMessage` (not the `feedMessage`, which will be a subset of the `combinedFeedMessage`), and all other rules should ignore the `combinedFeedMessage` and validate the `feedMessage`.

I'll open a PR shortly with this solution.

**Comment by barbeau** [comment]
PR at https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/270
